
import React, { useEffect, useState, useCallback } from 'react';
import { fetchCryptoData } from './services/binanceService';
import { analyzeCrypto } from './services/geminiService';
import { CryptoData, PredictionResult, Interval, Language } from './types';
import CryptoCard from './components/CryptoCard';
import { Activity, AlertOctagon, Github, Info, Clock, Languages } from 'lucide-react';

const SYMBOLS = ['BTCUSDT', 'ETHUSDT', 'SOLUSDT','ZECUSDT'];
const INTERVALS: Interval[] = ['15m', '1h', '4h', '1d'];

const App: React.FC = () => {
  const [cryptoData, setCryptoData] = useState<Record<string, CryptoData>>({});
  const [predictions, setPredictions] = useState<Record<string, PredictionResult>>({});
  const [loadingData, setLoadingData] = useState<boolean>(true);
  const [loadingPredictions, setLoadingPredictions] = useState<Record<string, boolean>>({});
  const [error, setError] = useState<string | null>(null);
  const [currentInterval, setCurrentInterval] = useState<Interval>('1h');
  const [language, setLanguage] = useState<Language>('en');

  // Translations
  const t = {
    title: language === 'zh' ? "加密货币AI预测" : "CryptoPredict AI",
    marketOutlook: language === 'zh' ? "市场展望" : "Market Outlook",
    description: language === 'zh' 
      ? `由 Gemini 2.5 支持的实时价格行为分析。我们计算 RSI、MACD、布林带和 EMA，为接下来的 ${currentInterval} 走势生成即时概率。`
      : `Real-time price action analysis powered by Gemini 2.5. We calculate RSI, MACD, Bollinger Bands, and EMAs to generate instant probabilities for the next ${currentInterval} movement.`,
    binanceLive: language === 'zh' ? "币安实况" : "Binance Live",
    disclaimerTitle: language === 'zh' ? "免责声明：" : "Disclaimer:",
    disclaimerText: language === 'zh'
      ? "本应用仅供演示和娱乐。提供的预测由AI模型基于技术指标生成，不构成财务建议。加密货币交易涉及重大风险。做出投资决定前请务必自行研究。"
      : "This application is for demonstration and entertainment purposes only. The predictions provided are generated by an AI model based on technical indicators and do not constitute financial advice. Cryptocurrency trading involves significant risk. Always do your own research before making investment decisions.",
    retry: language === 'zh' ? "重试" : "Retry",
    errorFetch: language === 'zh' ? "无法从币安获取数据。请检查您的网络连接。" : "Failed to fetch data from Binance. Please check your connection.",
    errorGeneric: language === 'zh' ? "获取市场数据时发生意外错误。" : "An unexpected error occurred while fetching market data.",
    errorAnalysis: language === 'zh' ? "分析失败。请确保您拥有有效的 Gemini API 密钥。" : "Analysis failed. Please ensure you have a valid Gemini API Key."
  };

  const initData = useCallback(async () => {
    setLoadingData(true);
    setError(null);
    try {
      const results = await Promise.all(SYMBOLS.map(sym => fetchCryptoData(sym, currentInterval)));
      const dataMap: Record<string, CryptoData> = {};
      results.forEach(res => {
        if (res) dataMap[res.symbol] = res;
      });
      setCryptoData(dataMap);
      if (Object.keys(dataMap).length === 0) {
        setError(t.errorFetch);
      }
    } catch (err) {
      setError(t.errorGeneric);
    } finally {
      setLoadingData(false);
    }
  }, [currentInterval, language]); // Added language to dependency to update error messages if needed

  useEffect(() => {
    initData();
    // Auto-refresh data every 60 seconds
    const interval = setInterval(initData, 60000);
    return () => clearInterval(interval);
  }, [initData]);

  // Clear predictions when interval changes, as old predictions are for different timeframe
  useEffect(() => {
    setPredictions({});
  }, [currentInterval]);

  const handleAnalyze = async (symbol: string) => {
    const data = cryptoData[symbol];
    if (!data) return;

    setLoadingPredictions(prev => ({ ...prev, [symbol]: true }));
    try {
      const result = await analyzeCrypto(data, language);
      setPredictions(prev => ({ ...prev, [symbol]: result }));
    } catch (err) {
      console.error(err);
      alert(t.errorAnalysis);
    } finally {
      setLoadingPredictions(prev => ({ ...prev, [symbol]: false }));
    }
  };

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'en' ? 'zh' : 'en');
  };

  return (
    <div className="min-h-screen pb-12 bg-slate-950 bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-indigo-900/20 via-slate-950 to-slate-950">
      
      {/* Header */}
      <header className="sticky top-0 z-50 backdrop-blur-lg border-b border-slate-800 bg-slate-950/80">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-16 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="bg-indigo-600 p-2 rounded-lg shadow-lg shadow-indigo-500/30">
              <Activity className="text-white" size={24} />
            </div>
            <h1 className="text-xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-white to-slate-400">
              {t.title}
            </h1>
          </div>
          <div className="flex items-center gap-4">
             <div className="hidden sm:flex items-center gap-2 text-xs font-medium text-emerald-400 bg-emerald-900/20 px-3 py-1.5 rounded-full border border-emerald-900/50">
               <span className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse"></span>
               {t.binanceLive}
             </div>
             
             {/* Language Switcher */}
             <button 
                onClick={toggleLanguage}
                className="flex items-center gap-1.5 text-sm text-slate-400 hover:text-white transition-colors border border-slate-800 hover:border-slate-600 rounded-md px-3 py-1.5 bg-slate-900/50"
             >
                <Languages size={16} />
                <span className="font-medium">{language === 'en' ? 'EN' : '中文'}</span>
             </button>

             <a href="https://github.com" target="_blank" rel="noreferrer" className="text-slate-400 hover:text-white transition-colors">
               <Github size={20} />
             </a>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 mt-8">
        
        <div className="flex flex-col md:flex-row md:items-end justify-between gap-6 mb-8">
          <div className="text-center sm:text-left">
            <h2 className="text-3xl font-bold text-white mb-2">{t.marketOutlook}</h2>
            <p className="text-slate-400 max-w-2xl">
              {t.description}
            </p>
          </div>

          <div className="flex items-center gap-2 bg-slate-900/50 p-1.5 rounded-lg border border-slate-800 self-center md:self-end">
             <div className="px-2 text-slate-500">
               <Clock size={16} />
             </div>
             {INTERVALS.map(int => (
               <button
                 key={int}
                 onClick={() => setCurrentInterval(int)}
                 className={`
                   px-3 py-1.5 rounded-md text-xs font-semibold transition-all
                   ${currentInterval === int 
                     ? 'bg-indigo-600 text-white shadow-lg shadow-indigo-500/25' 
                     : 'text-slate-400 hover:text-white hover:bg-slate-800'}
                 `}
               >
                 {int.toUpperCase()}
               </button>
             ))}
          </div>
        </div>

        {error && (
          <div className="mb-8 bg-rose-900/20 border border-rose-800 text-rose-200 p-4 rounded-xl flex items-center gap-3">
            <AlertOctagon className="shrink-0" />
            <p>{error}</p>
            <button onClick={initData} className="ml-auto text-sm bg-rose-800 hover:bg-rose-700 px-3 py-1 rounded transition">{t.retry}</button>
          </div>
        )}

        {loadingData && Object.keys(cryptoData).length === 0 ? (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
             {[1,2,3].map(i => (
               <div key={i} className="h-[500px] bg-slate-800/30 rounded-xl animate-pulse border border-slate-800"></div>
             ))}
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {SYMBOLS.map(symbol => {
              const data = cryptoData[symbol];
              if (!data) return null; // Should not happen if loading is handled
              return (
                <CryptoCard
                  key={symbol}
                  data={data}
                  prediction={predictions[symbol] || null}
                  loadingPrediction={loadingPredictions[symbol] || false}
                  onAnalyze={() => handleAnalyze(symbol)}
                  language={language}
                />
              );
            })}
          </div>
        )}

        {/* Disclaimer */}
        <div className="mt-12 bg-slate-900/50 border border-slate-800 rounded-lg p-4 flex items-start gap-3">
          <Info className="text-slate-500 shrink-0 mt-0.5" size={18} />
          <div className="text-xs text-slate-500 leading-relaxed">
            <strong className="text-slate-400">{t.disclaimerTitle}</strong> {t.disclaimerText}
          </div>
        </div>

      </main>
    </div>
  );
};

export default App;
